language: ruby
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fd47d756d2b5_key -iv $encrypted_fd47d756d2b5_iv
  -in id_rsa_worker.enc -out ~/id_rsa_worker -d
- chmod 600 ~/id_rsa_worker
- docker build --tag=validation_worker .
script:
- docker run -it -v ~/id_rsa_worker:/root/.ssh/id_rsa_worker validation_worker
  bash -c "source test/e2e-test_positive_verification.sh"
