language: ruby
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fd47d756d2b5_key -iv $encrypted_fd47d756d2b5_iv
  -in id_rsa_worker.enc -out ./id_rsa_worker -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa_worker
- docker build --tag=validation_worker .
script:
- docker run -it -v ~/powersoftau/id_rsa_worker:/root/.ssh/id_rsa_worker -e CONSTRAINED=true -e
  SSH_USER=validationworker -e SFTP_ADDRESS=trusted-setup.staging.gnosisdev.com -e
  DATE_OF_NEWEST_CONTRIBUTION=1 -e TRUSTED_SETUP_TURN=1 -e MAKEFIRSTCONTRIBUTION=yes
  -e KEY_GITTER_TRUSTED_SETUP_ROOM=$KEY_GITTER_TRUSTED_SETUP_ROOM validation_worker
  bash -c "source test/e2e-test_positive_verification.sh"
