[package]
name = "powersoftau"
version = "0.2.0"
authors = ["Sean Bowe", "Alex Vlasov"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "Communal zk-SNARK MPC for Public Parameters"
documentation = "https://docs.rs/powersoftau/"
homepage = "https://github.com/matter-labs/powersoftau"
repository = "https://github.com/matter-labs/powersoftau"

[dependencies]
rand = "0.4"
crossbeam = "0.3.0"
num_cpus = "1.7.0"
blake2 = "0.6.1"
generic-array = "0.8.3"
typenum = "1.9.0"
byteorder = "1.1.0"
hex-literal = "0.1"
rust-crypto = "0.2"

memmap = "0.7.0"
itertools = "0.8.0"

ff = { git = 'https://github.com/matterinc/ff', features = ["derive"] }
pairing = { git = 'https://github.com/matterinc/pairing', features = ["expose-arith"]}
bellman = { git = 'https://github.com/matterinc/bellman'}

#ff = { git = 'https://github.com/matterinc/ff', features = ["derive"], rev = "056a13b9" }
#pairing = { git = 'https://github.com/matterinc/pairing', features = ["expose-arith"], rev = "84b57df3" }
#bellman = { git = 'https://github.com/matterinc/bellman', rev = "e775b47d"}

#[patch.'https://https://github.com/matterinc/ff']
#ff = { git = 'https://github.com/matterinc/ff', features = ["derive"], rev = "056a13b9" }

#[patch.'https://https://github.com/matterinc/pairing']
#pairing = { git = 'https://github.com/matterinc/pairing', features = ["expose-arith"], rev = "84b57df3" }

[features]

